services:
  app:
    container_name: vegetables-shop
    image: vegetables-shop:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DASHBOARD_USER=${DASHBOARD_USER}
      - DASHBOARD_PASSWORD=${DASHBOARD_PASSWORD}
      - GOOGLE_SHEET_ID=${GOOGLE_SHEET_ID}
      - GOOGLE_SHEET_NAME=${GOOGLE_SHEET_NAME}
      - GOOGLE_SHEET_ORDERS_ID=${GOOGLE_SHEET_ORDERS_ID}
      - GOOGLE_SHEET_ORDERS_NAME=${GOOGLE_SHEET_ORDERS_NAME}
      - GOOGLE_CLIENT_EMAIL=${GOOGLE_CLIENT_EMAIL}
      - GOOGLE_PRIVATE_KEY=${GOOGLE_PRIVATE_KEY}
      - TZ=Europe/Berlin
    volumes:
      - ./.next/static:/app/.next/static
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
